In [1]:
# Importing pandas and numpy python libraries
import pandas as pd
import numpy as np

In [2]:
# Printing
print("Hello World")

Hello World

In [3]:
# Variable assignment
x = 5  # Integer
y = 3  # Integer

# Arithmetic operations
print(x + y)  # Addition
print(x * y)  # Multiplication
print(x ** y)  # Exponentiation
print(x / y)  # Division

# Assigning result to a new variable
z = x + y
print(z)

8
15
125
1.6666666666666667
8

In [4]:
# Logical comparisons
print(x > y)   # Greater than
print(x == y)  # Equal to
print(x != y)  # Not equal to

True
False
True

In [5]:
# Combining variables into a list
all_variables = [x, y, z]

In [6]:
# Different types of variables
int_var = 10                   # Integer
num_var = 10.5                 # Float (numeric)
char_var = "Hello"             # String (character)
bool_var = True                # Boolean (logical)
complex_var = 3 + 4j           # Complex number
list_var = [1, 2, 3]           # List
tuple_var = (4, 5, 6)          # Tuple
set_var = {7, 8, 9}            # Set
dict_var = {"a": 1, "b": 2}    # Dictionary
none_var = None                # NoneType

# Checking variable type
print(type(int_var))      # <class 'int'>
print(type(num_var))      # <class 'float'>
print(type(char_var))     # <class 'str'>
print(type(bool_var))     # <class 'bool'>
print(type(complex_var))  # <class 'complex'>
print(type(list_var))     # <class 'list'>
print(type(tuple_var))    # <class 'tuple'>
print(type(set_var))      # <class 'set'>
print(type(dict_var))     # <class 'dict'>
print(type(none_var))     # <class 'NoneType'>

<class 'int'>
<class 'float'>
<class 'str'>
<class 'bool'>
<class 'complex'>
<class 'list'>
<class 'tuple'>
<class 'set'>
<class 'dict'>
<class 'NoneType'>

In [7]:
# Creating a NumPy array (numeric vector)
vec_num = np.array([1, 2, 3, 4, 5])
print(vec_num)

# NumPy arrays support vectorized operations
print(vec_num + 10)    # Add 10 to each element
print(vec_num * 2)     # Multiply each element by 2
print(vec_num > 3)     # Logical comparison

# Indexing works similarly to Python lists
print(vec_num[0])      # First element
print(vec_num[-1])     # Last element

# Slicing
print(vec_num[1:4])    # Elements from index 1 to 3 (Python is 0-based)

# Type and shape
print(vec_num.shape)   # (5,)

[1 2 3 4 5]
[11 12 13 14 15]
[ 2  4  6  8 10]
[False False False  True  True]
1
5
[2 3 4]
(5,)

In [8]:
# Python list
py_list = [1, 2, 3, 4, 5]

# Creating empty list 
add_ten = []

# Adding 10 to each element and appending to the empty list
for x in py_list:
    add_ten.append(x+10)

    
print(add_ten)

# With NumPy array (vectorized)
np_array = np.array(py_list)
print(np_array + 10)

[11, 12, 13, 14, 15]
[11 12 13 14 15]

In [9]:
# Create the DataFrame
count_data = pd.DataFrame({
    "Gene": ["Gene1", "Gene2"],
    "Sample1": [100, 200],
    "Sample2": [150, 250]
})

# Display the DataFrame
count_data

    Gene  Sample1  Sample2
0  Gene1      100      150
1  Gene2      200      250

In [10]:
# Step 1: Read RNA-seq raw counts CSV from GitHub
url = 'https://raw.githubusercontent.com/jimmyrouse/BSR/main/Tumor_vs_Normal_counts.csv'
df_counts = pd.read_csv(url)
df_counts.head()

     Gene  Tumor_1  Tumor_2  Tumor_3  Normal_1  Normal_2  Normal_3
0    TP53       92      114      111        89       100       104
1    EGFR      107       94      111        85        80       100
2     MYC      101      101      114        89        82        97
3    KRAS      130      100      124        69        68        90
4  PIK3CA      106       98       92        99        99       111

In [11]:
# Step 2: Set the 'Gene' column as the index 
df_counts.set_index('Gene', inplace=True)

df_counts.head()

        Tumor_1  Tumor_2  Tumor_3  Normal_1  Normal_2  Normal_3
Gene
TP53         92      114      111        89       100       104
EGFR        107       94      111        85        80       100
MYC         101      101      114        89        82        97
KRAS        130      100      124        69        68        90
PIK3CA      106       98       92        99        99       111

In [12]:
# Step 3: CPM Normalization
# Calculate column sums (total counts per sample)
#axis=0 calcualtes the sum DOWN the columns
total_counts = df_counts.sum(axis=0)

total_counts

Tumor_1     4903
Tumor_2     4993
Tumor_3     4886
Normal_1    5043
Normal_2    4860
Normal_3    5021
dtype: int64

In [13]:
# Divide each value by the column's total count, then multiply by 1e6
df_cpm = df_counts.div(total_counts, axis=1) * 1e6

# Step 4: Save the CPM-normalized data to a CSV
#df_cpm.to_csv("Tumor_vs_Normal_CPM.csv")

# Preview
print("CPM-normalized data:")
df_cpm.head()

CPM-normalized data:

,Tumor_1,Tumor_2,Tumor_3,Normal_1,Normal_2,Normal_3
Gene,,,,,,
TP53,18764.022027,22831.964751,22717.969709,17648.225263,20576.131687,20713.005377
EGFR,21823.373445,18826.356900,22717.969709,16855.046599,16460.905350,19916.351324
MYC,20599.632878,20228.319648,23331.968891,17648.225263,16872.427984,19318.860785
KRAS,26514.378952,20028.039255,25378.632828,13682.331945,13991.769547,17924.716192
PIK3CA,21619.416684,19627.478470,18829.308228,19631.171921,20370.370370,22107.149970

In [14]:
# First column (all rows)
col1 = df_cpm.iloc[:, 0]
print("First column (all rows):")
col1.head(10)

First column (all rows):

Gene
TP53      18764.022027
EGFR      21823.373445
MYC       20599.632878
KRAS      26514.378952
PIK3CA    21619.416684
MET       23047.114012
AKT1      22231.286967
CTNNB1    24066.897818
BCL2      17744.238221
VEGFA     18560.065266
Name: Tumor_1, dtype: float64

In [15]:
# First row (all columns)
row1 = df_cpm.iloc[0, :]
print("First row (all columns):")
row1

First row (all columns):

Tumor_1     18764.022027
Tumor_2     22831.964751
Tumor_3     22717.969709
Normal_1    17648.225263
Normal_2    20576.131687
Normal_3    20713.005377
Name: TP53, dtype: float64

In [16]:
# Columns 1 to 3 (all rows)
cols_1_to_3 = df_cpm.iloc[:, 0:3]
print("Columns 1 to 3")
cols_1_to_3.head()

Columns 1 to 3

             Tumor_1       Tumor_2       Tumor_3
Gene
TP53    18764.022027  22831.964751  22717.969709
EGFR    21823.373445  18826.356900  22717.969709
MYC     20599.632878  20228.319648  23331.968891
KRAS    26514.378952  20028.039255  25378.632828
PIK3CA  21619.416684  19627.478470  18829.308228

In [17]:
# Columns 4 to 6 (all rows)
cols_4_to_6 = df_cpm.iloc[:, 3:6]
print("Columns 4 to 6 (all rows):")
cols_4_to_6.head()

Columns 4 to 6 (all rows):

            Normal_1      Normal_2      Normal_3
Gene
TP53    17648.225263  20576.131687  20713.005377
EGFR    16855.046599  16460.905350  19916.351324
MYC     17648.225263  16872.427984  19318.860785
KRAS    13682.331945  13991.769547  17924.716192
PIK3CA  19631.171921  20370.370370  22107.149970

In [18]:
# Single value at first row, first column
value_0_0 = df_cpm.iloc[0, 0]
print("Single value at first row, first column:")
print(value_0_0)

Single value at first row, first column:
18764.022027330207

In [19]:
####################PANDAS ON CPM MATRIX##############

# Overview of the DataFrame
df_cpm.info()

# Summary statistics
df_cpm.describe()

<class 'pandas.core.frame.DataFrame'>
Index: 50 entries, TP53 to PRKAR1A
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Tumor_1   50 non-null     float64
 1   Tumor_2   50 non-null     float64
 2   Tumor_3   50 non-null     float64
 3   Normal_1  50 non-null     float64
 4   Normal_2  50 non-null     float64
 5   Normal_3  50 non-null     float64
dtypes: float64(6)
memory usage: 2.7+ KB

,Tumor_1,Tumor_2,Tumor_3,Normal_1,Normal_2,Normal_3
count,50.000000,50.000000,50.000000,50.000000,50.000000,50.000000
mean,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000
std,2540.548095,2855.423301,3081.263902,2857.322660,3266.095107,2639.778020
min,15704.670610,13819.347086,12075.317233,13682.331945,13786.008230,15733.917546
25%,18356.108505,17875.025035,18215.309046,17697.798929,17952.674897,17974.507070
50%,19885.784214,19827.758862,20466.639378,19829.466587,19444.444444,20015.933081
75%,21517.438303,21430.002003,22666.803111,22010.707912,22222.222222,21509.659430
max,26514.378952,27238.133387,25378.632828,25778.306564,26954.732510,28480.382394

In [20]:
df_cpm['Normal_Mean'] = df_cpm.iloc[:, 3:6].mean(axis=1)

df_cpm['Tumor_Mean'] = df_cpm.iloc[:, 0:3].mean(axis=1)

# Calculate difference (Tumor - Normal)
df_cpm['Difference'] = df_cpm['Tumor_Mean'] - df_cpm['Normal_Mean']

# View the updated DataFrame
df_cpm[['Normal_Mean', 'Tumor_Mean', 'Difference']].head()

         Normal_Mean    Tumor_Mean   Difference
Gene
TP53    19645.787442  21437.985496  1792.198053
EGFR    17744.101091  21122.566685  3378.465593
MYC     17946.504677  21386.640472  3440.135795
KRAS    15199.605895  23973.683678  8774.077784
PIK3CA  20702.897421  20025.401127  -677.496294

In [21]:
# Add a ranking column based on Difference
df_cpm['Rank'] = df_cpm['Difference'].rank(ascending=False)

# View top 5 upregulated genes
df_cpm[['Normal_Mean', 'Tumor_Mean', 'Difference', 'Rank']].sort_values(by='Difference', ascending=False).head()

         Normal_Mean    Tumor_Mean   Difference  Rank
Gene
KRAS    15199.605895  23973.683678  8774.077784   1.0
MAPK1   16826.536549  24085.661552  7259.125003   2.0
AKT1    18170.674685  24676.462536  6505.787850   3.0
PTEN    16472.604682  22519.670343  6047.065661   4.0
CTNNB1  17201.712434  23192.452756  5990.740322   5.0

In [22]:
# Calculate fold change and log2 fold change
df_cpm['Fold_Change'] = (df_cpm['Tumor_Mean'] + 1) / (df_cpm['Normal_Mean'] + 1)
df_cpm['Log2_FC'] = np.log2(df_cpm['Fold_Change'])

# View top genes with highest log2 fold change
df_cpm[['Normal_Mean', 'Tumor_Mean','Fold_Change', 'Log2_FC']].sort_values(by='Log2_FC', ascending=False).head()

         Normal_Mean    Tumor_Mean  Fold_Change   Log2_FC
Gene
KRAS    15199.605895  23973.683678     1.577219  0.657383
MAPK1   16826.536549  24085.661552     1.431384  0.517410
PTEN    16472.604682  22519.670343     1.367076  0.451093
AKT1    18170.674685  24676.462536     1.358018  0.441503
CTNNB1  17201.712434  23192.452756     1.348244  0.431082

In [23]:
# Importing library to perform t-test
from scipy.stats import ttest_ind

In [24]:
# Creating data frames of normal and tumor samples
normal_vals = df_cpm.iloc[:, 3:6]
tumor_vals = df_cpm.iloc[:, 0:3]

normal_vals.head()

            Normal_1      Normal_2      Normal_3
Gene
TP53    17648.225263  20576.131687  20713.005377
EGFR    16855.046599  16460.905350  19916.351324
MYC     17648.225263  16872.427984  19318.860785
KRAS    13682.331945  13991.769547  17924.716192
PIK3CA  19631.171921  20370.370370  22107.149970

In [25]:
# Apply t-test row-wise
ttest_results = ttest_ind(tumor_vals.values, normal_vals.values, axis=1, equal_var=False)

# Add p-values to dataframe
df_cpm['p_value'] = ttest_results.pvalue

df_cpm[['Normal_Mean', 'Tumor_Mean','Fold_Change', 'Log2_FC', 'p_value']].sort_values(by='Log2_FC', ascending=False).head()

         Normal_Mean    Tumor_Mean  Fold_Change   Log2_FC   p_value
Gene
KRAS    15199.605895  23973.683678     1.577219  0.657383  0.027548
MAPK1   16826.536549  24085.661552     1.431384  0.517410  0.000128
PTEN    16472.604682  22519.670343     1.367076  0.451093  0.002597
AKT1    18170.674685  24676.462536     1.358018  0.441503  0.080380
CTNNB1  17201.712434  23192.452756     1.348244  0.431082  0.019674

In [26]:
## By default the label column will be not significant
df_cpm['Label'] = 'Not Significant'

# Define significance thresholds
p_thresh = 0.05     # Adjusted p-value

## Classify gene as upregulated of Log2 FC is greater than 0 and p-value is significant
## Classify gene as downregulated of Log2 FC is less than 0 and p-value is significant

df_cpm.loc[(df_cpm['Log2_FC'] > 0) & (df_cpm['p_value'] < p_thresh), 'Label'] = 'Upregulated'
df_cpm.loc[(df_cpm['Log2_FC'] < 0) & (df_cpm['p_value'] < p_thresh), 'Label'] = 'Downregulated'

# Count how many upregulated and downregulated genes there are
df_cpm['Label'].value_counts()

Label
Not Significant    36
Downregulated       8
Upregulated         6
Name: count, dtype: int64

In [27]:
##### JOINING METADATA

# Meta data 1
meta_data_1 = pd.DataFrame({
    "Sample": ["Normal_1", "Normal_2", "Normal_3", "Tumor_1"],
    "Group": ["Normal", "Normal", "Normal", "Tumor"],
    "Condition": ["Healthy", "Healthy", "Healthy", "Cancer"]
})

# Meta data 2
meta_data_2 = pd.DataFrame({
    "Sample": ["Normal_2", "Tumor_1", "Tumor_2", "Tumor_3"],
    "Batch": ["A", "B", "B", "C"]
})

In [28]:
# Left join: keep all rows from meta_data_1
left_join_result = meta_data_1.merge(meta_data_2, on="Sample", how="left")

# Full join: union of both datasets
full_join_result = meta_data_1.merge(meta_data_2, on="Sample", how="outer")

# Inner join: intersection (only matching "Sample")
inner_join_result = meta_data_1.merge(meta_data_2, on="Sample", how="inner")

In [29]:
print("Left Join Result:")
print(left_join_result)


print("\nFull Join Result:")
print(full_join_result)

print("\nInner Join Result:")
print(inner_join_result)

Left Join Result:
     Sample   Group Condition Batch
0  Normal_1  Normal   Healthy   NaN
1  Normal_2  Normal   Healthy     A
2  Normal_3  Normal   Healthy   NaN
3   Tumor_1   Tumor    Cancer     B

Full Join Result:
     Sample   Group Condition Batch
0  Normal_1  Normal   Healthy   NaN
1  Normal_2  Normal   Healthy     A
2  Normal_3  Normal   Healthy   NaN
3   Tumor_1   Tumor    Cancer     B
4   Tumor_2     NaN       NaN     B
5   Tumor_3     NaN       NaN     C

Inner Join Result:
     Sample   Group Condition Batch
0  Normal_2  Normal   Healthy     A
1   Tumor_1   Tumor    Cancer     B